package env

const (
	API_KEY_ENV_VAR                  = "COINMARKETCAP_API_KEY"
	API_ENDPOINT_ENV_VAR             = "COINMARKETCAP_API_ENDPOINT"
	CLICKHOUSE_CONNECTION_STRING_VAR = "CLICKHOUSE_CONNECTION_STRING"
	NEED_MIGRATION_VAR               = "NEED_MIGRATION"
)
