package env

const (
	API_KEY_VAR                    = "COINMARKETCAP_API_KEY"
	API_ENDPOINT_VAR               = "COINMARKETCAP_API_ENDPOINT"
	DATABASE_CONNECTION_STRING_VAR = "DATABASE_CONNECTION_STRING"
	NEED_MIGRATION_VAR             = "NEED_MIGRATION"
	CONFIG_DIR_VAR                 = "CONFIG_DIR"
)
